In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#4-2-1 generator function that generates 10 integers and use it to build an array

def generate():
    for i in range(10):
        yield i
array = np.fromiter(generate(), dtype=float)
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [4]:
#4.2.2 two random array A and B, check if they are equal

A = np.random.randint(0, 10, 5)
B = np.random.randint(0, 10, 5)
equal = np.allclose(A, B)
print(A)
print(B)
if(equal):
    print("They are equal")
else:
    print("Not equal") 

[6 2 2 8 0]
[0 4 8 7 2]
Not equal


In [5]:
#4.2.3 random vector with shape (100,2) representing coordinates, find point by point distances

vector = np.random.random((100, 2))
x, y = np.atleast_2d(vector[:,0], vector[:,1])
distance = np.sqrt(pow((x-x.T),2)+pow((y-y.T), 2))
print(distance)

[[0.         0.3207501  0.85315083 ... 0.85768398 0.83042448 1.27773578]
 [0.3207501  0.         0.57726668 ... 0.62766512 0.57828637 0.95854974]
 [0.85315083 0.57726668 0.         ... 0.17110256 0.78188655 0.5551885 ]
 ...
 [0.85768398 0.62766512 0.17110256 ... 0.         0.92956371 0.70251015]
 [0.83042448 0.57828637 0.78188655 ... 0.92956371 0.         0.77243992]
 [1.27773578 0.95854974 0.5551885  ... 0.70251015 0.77243992 0.        ]]


In [6]:
#4.2.4 Subtract the mean of each row of a matrix

matrix = np.random.rand(3, 4)
sub = matrix - matrix.mean(axis=1, keepdims=True)
print(matrix)
print(sub)

[[2.84642235e-01 8.52759303e-01 5.13317661e-01 9.42294287e-02]
 [8.75200996e-01 1.11551866e-01 9.76493944e-01 8.05606884e-01]
 [4.36580236e-01 5.27595256e-02 4.65786509e-01 6.66520704e-04]]
[[-0.15159492  0.41652215  0.0770805  -0.34200773]
 [ 0.18298757 -0.58066156  0.28428052  0.11339346]
 [ 0.19763204 -0.18618867  0.22683831 -0.23828168]]


In [7]:
#4.2.5 sort an array by the nth column

new_arr = np.random.randint(0, 10, (5,5))
n = 2
sorted = new_arr[new_arr[:,n].argsort()]
print(new_arr)
print(sorted)

[[3 6 4 7 7]
 [8 7 4 9 2]
 [9 5 7 8 2]
 [4 5 9 9 8]
 [3 1 9 0 7]]
[[3 6 4 7 7]
 [8 7 4 9 2]
 [9 5 7 8 2]
 [4 5 9 9 8]
 [3 1 9 0 7]]


In [8]:
#4.2.6 Compute a matrix rank

new_matrix = np.random.randint(0, 10, (5,5))
rank = np.linalg.matrix_rank(new_matrix)
print(new_matrix)
print("rank of the matrix:", rank)

[[0 2 1 4 4]
 [7 8 8 6 1]
 [3 0 5 3 0]
 [3 3 7 1 0]
 [3 2 3 1 6]]
rank of the matrix: 5


In [9]:
#4.2.6 get the block-sum (block size is 4x4)

arr = np.random.random((16,16))
k = 4
sum = np.add.reduceat(np.add.reduceat(arr, np.arange(0, arr.shape[0], k), axis=0),np.arange(0, arr.shape[1], k), axis=1)
print(arr)
print("sum:", sum)

[[0.02793227 0.61715403 0.07226359 0.19770125 0.95580046 0.89508039
  0.55177816 0.54730446 0.03736269 0.94259698 0.3485098  0.83170544
  0.70277547 0.14850053 0.02476816 0.43676868]
 [0.84836597 0.89847178 0.86877296 0.7009896  0.1385436  0.21713118
  0.01238481 0.32057286 0.39123419 0.86481901 0.60717191 0.57208249
  0.63089129 0.22966115 0.59618236 0.70886931]
 [0.12843553 0.88165342 0.10744807 0.0108039  0.20969485 0.07573993
  0.05852807 0.97321097 0.65629394 0.23592568 0.77898962 0.06066221
  0.70198513 0.28540786 0.45750303 0.26682575]
 [0.04717664 0.5608943  0.32054821 0.39951681 0.54076405 0.8614471
  0.84473496 0.73853147 0.66441702 0.32387354 0.52590436 0.23779804
  0.96191968 0.45738153 0.76272965 0.27819838]
 [0.08766004 0.25267507 0.93868445 0.14274249 0.51591121 0.4319317
  0.79991532 0.39633967 0.17583403 0.51162406 0.08633149 0.28247919
  0.18771627 0.01964888 0.22238505 0.88275162]
 [0.47223067 0.11728462 0.19766561 0.90983317 0.75677442 0.8193171
  0.126536   0.01983