In [8]:
import numpy as np

In [9]:
#4.1.1 Create a vector with values ranging from 10 to 49. Reverse a vector (first element becomes last)

vector = np.arange(10,50)
print(vector)

reverse = np.flip(vector)
print(reverse)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [11]:
#4.1.2 Create a 5x5 array with random values. and find the minimum and maximum values

matrix = np.random.random((5,5))
print(matrix)
minimum = matrix.min()
maximum = matrix.max()

print("minimum:", minimum)
print("maximum:", maximum)

[[0.11681752 0.9092574  0.34302674 0.28104084 0.70814171]
 [0.85699303 0.05737507 0.0206789  0.57168415 0.50151393]
 [0.00483651 0.54930172 0.49756992 0.17025624 0.72567843]
 [0.3639825  0.98322341 0.36146507 0.28099083 0.07191247]
 [0.36637354 0.96673964 0.07327454 0.24158707 0.8239998 ]]
minimum: 0.004836509364287589
maximum: 0.9832234109368284


In [12]:
# 4.1.3 Normalize a 5x5 random matrix


b_matrix = np.random.random((5,5))
b_minimum = b_matrix.min()
b_maximum = b_matrix.max()

m_matrix = (b_matrix - b_minimum) / (b_maximum - b_minimum)
print("Normalized Matrix:", m_matrix)

Normalized Matrix: [[0.32743873 0.69626895 0.95382662 0.15725585 0.56302473]
 [0.08375095 0.46679591 0.59670061 0.12738023 0.00422808]
 [0.06091571 0.16074309 0.94016857 0.97381365 1.        ]
 [0.58986318 0.04279391 0.50179024 0.         0.22253925]
 [0.69837356 0.22996347 0.49021203 0.48663969 0.86412757]]


In [13]:
#4.1.5 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

matrixa = np.random.random((5,3))
matrixb = np.random.random((3,2))

multiply = np.dot(matrixa, matrixb)
print("Multiply Result:", multiply)

Multiply Result: [[1.52409477 0.57955828]
 [1.60064124 0.51562062]
 [1.0709336  0.30391787]
 [1.49871907 0.80375252]
 [1.39389851 0.73803683]]


In [14]:
#4.1.6 How to get the dates of yesterday, today and tomorrow?

today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print("today date:", today)
print("yesterday date:", yesterday)
print("tomorrow date:", tomorrow)

today date: 2023-02-09
yesterday date: 2023-02-08
tomorrow date: 2023-02-10


In [15]:
#4.1.6 Extract the integer part of a random array using 5 different methods array = np.random.uniform(0, 10, 10)

print("array:\n", array)
print(np.floor(array))
print(array-array%1)
print(np.ceil(array)-1)
print(array.astype(int))
print(np.trunc(array))

array:
 [8.24268282 8.25727567 7.84686029 5.55134711 6.04621465 8.38593042
 3.05613284 9.75297443 6.0918205  7.74103602]
[8. 8. 7. 5. 6. 8. 3. 9. 6. 7.]
[8. 8. 7. 5. 6. 8. 3. 9. 6. 7.]
[8. 8. 7. 5. 6. 8. 3. 9. 6. 7.]
[8 8 7 5 6 8 3 9 6 7]
[8. 8. 7. 5. 6. 8. 3. 9. 6. 7.]


In [16]:
#4.1.7 Create a structured array representing a position (x,y) and a color (r,g,b)

structure = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]), ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)] )])

print(structure)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\HP\AppData\Local\Temp\ipykernel_11984\4025786590.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  structure = np.zeros(10, [('position', [('x', float, 1), ('y', float, 1)]), ('color', [('r', float, 1), ('g', float, 1), ('b', float, 1)] )])
